name: Build Vocal Lab

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4



    - name: Configure CMake
      id: cmake_config
      continue-on-error: true
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release > cmake_log.txt 2>&1

    - name: Upload CMake Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CMake_Log_${{ matrix.os }}
        path: cmake_log.txt

    - name: Build
      run: cmake --build build --config Release

    - name: Package Mac Artifacts
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p VocalLab_Mac_Release
        cp -r "build/VocalLab_artefacts/VST3/Vocal Lab.vst3" VocalLab_Mac_Release/
        cp -r "build/VocalLab_artefacts/AU/Vocal Lab.component" VocalLab_Mac_Release/
        cp -r "build/VocalLab_artefacts/Standalone/Vocal Lab.app" VocalLab_Mac_Release/
        zip -r VocalLab_Mac_Release.zip VocalLab_Mac_Release/

    - name: Upload Mac Artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: VocalLab_Mac_Release
        path: VocalLab_Mac_Release.zip

    - name: Build Windows Installer
      if: matrix.os == 'windows-latest'
      run: |
        # Download and install Inno Setup on the Windows runner
        choco install innosetup -y
        # Compile the installer
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" VocalLabInstaller.iss

    - name: Upload Windows Artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: VocalLab_Windows_Installer
        path: Installer/VocalLab_Installer_v1.0.0.exe
